if(NOT DEFINED MINEBACKUP_REPOSITORY_ROOT)
    message(FATAL_ERROR "MINEBACKUP_REPOSITORY_ROOT is required")
endif()

set(MINEBACKUP_SOURCE_DIR ${MINEBACKUP_REPOSITORY_ROOT}/MineBackup)
set(MINEBACKUP_SRC_DIR ${MINEBACKUP_SOURCE_DIR}/src)
set(MINEBACKUP_APP_DIR ${MINEBACKUP_SRC_DIR}/app)
set(MINEBACKUP_CORE_DIR ${MINEBACKUP_SRC_DIR}/core)
set(MINEBACKUP_INFRA_DIR ${MINEBACKUP_SRC_DIR}/infra)
set(MINEBACKUP_PLATFORM_DIR ${MINEBACKUP_SRC_DIR}/platform)
set(MINEBACKUP_UI_DIR ${MINEBACKUP_SRC_DIR}/ui)
set(MINEBACKUP_UTILS_DIR ${MINEBACKUP_SRC_DIR}/utils)
set(MINEBACKUP_THIRD_PARTY_DIR ${MINEBACKUP_SOURCE_DIR}/third_party)
set(MINEBACKUP_IMGUI_DIR ${MINEBACKUP_THIRD_PARTY_DIR}/imgui)
set(MINEBACKUP_KNOTLINK_DIR ${MINEBACKUP_THIRD_PARTY_DIR}/knotlink-sdk-cpp-2.0)
include(${MINEBACKUP_REPOSITORY_ROOT}/cmake/MineBackupSources.cmake)

set(expected ${MINEBACKUP_MAIN_SOURCES} ${MINEBACKUP_DATA_CORE_SOURCES} ${MINEBACKUP_V15_DATA_SOURCES}
    ${MINEBACKUP_APPLICATION_SOURCES} ${MINEBACKUP_V15_DESKTOP_SOURCES}
    ${MINEBACKUP_UI_SOURCES} ${MINEBACKUP_WINDOWS_SOURCES} ${MINEBACKUP_IMGUI_SOURCES})
set(expected_relative)
foreach(path IN LISTS expected)
    file(RELATIVE_PATH relative "${MINEBACKUP_SOURCE_DIR}" "${path}")
    file(TO_CMAKE_PATH "${relative}" relative)
    string(TOLOWER "${relative}" relative)
    list(APPEND expected_relative "${relative}")
endforeach()
list(SORT expected_relative)
list(REMOVE_DUPLICATES expected_relative)

file(READ "${MINEBACKUP_SOURCE_DIR}/MineBackup.vcxproj" project_xml)
string(REGEX MATCHALL "<ClCompile Include=\"[^\"]+\"" compile_entries "${project_xml}")
set(actual_relative)
foreach(entry IN LISTS compile_entries)
    string(REGEX REPLACE ".*Include=\"([^\"]+)\".*" "\\1" relative "${entry}")
    string(REPLACE "\\" "/" relative "${relative}")
    string(TOLOWER "${relative}" relative)
    list(APPEND actual_relative "${relative}")
endforeach()
list(SORT actual_relative)
list(REMOVE_DUPLICATES actual_relative)

if(NOT expected_relative STREQUAL actual_relative)
    message(STATUS "CMake sources: ${expected_relative}")
    message(STATUS "MSBuild sources: ${actual_relative}")
    message(FATAL_ERROR "CMake and MSBuild source manifests differ")
endif()
message(STATUS "CMake and MSBuild compile source manifests match")
