if(NOT DEFINED MINEBACKUP_REPOSITORY_ROOT)
    message(FATAL_ERROR "MINEBACKUP_REPOSITORY_ROOT is required")
endif()
set(MINEBACKUP_SOURCE_DIR ${MINEBACKUP_REPOSITORY_ROOT}/MineBackup)
set(MINEBACKUP_SRC_DIR ${MINEBACKUP_SOURCE_DIR}/src)
include(${MINEBACKUP_REPOSITORY_ROOT}/cmake/MineBackupSources.cmake)

# Include all project headers, including header-only contracts without a .cpp.
file(GLOB_RECURSE project_files
    "${MINEBACKUP_SRC_DIR}/*.h" "${MINEBACKUP_SRC_DIR}/*.cpp" "${MINEBACKUP_SRC_DIR}/*.mm")
foreach(path IN LISTS project_files)
    get_filename_component(name "${path}" NAME)
    string(SHA256 key "${name}")
    get_property(previous GLOBAL PROPERTY "header_${key}")
    if(previous AND NOT previous STREQUAL path)
        message(FATAL_ERROR "Ambiguous project include name: ${name}")
    endif()
    set_property(GLOBAL PROPERTY "header_${key}" "${path}")
endforeach()

function(check_dependencies path origin chain)
    string(SHA256 visit "${origin}:${path}")
    get_property(seen GLOBAL PROPERTY "visited_${visit}")
    if(seen)
        return()
    endif()
    set_property(GLOBAL PROPERTY "visited_${visit}" TRUE)
    file(RELATIVE_PATH relative "${MINEBACKUP_SRC_DIR}" "${path}")
    string(REGEX MATCH "^[^/]+" layer "${relative}")
    set(allowed domain)
    if(NOT origin STREQUAL "domain")
        list(APPEND allowed infra)
    endif()
    if(origin STREQUAL "runtime" OR origin STREQUAL "cli")
        list(APPEND allowed runtime)
    endif()
    if(origin STREQUAL "cli")
        list(APPEND allowed cli)
    endif()
    if(NOT layer IN_LIST allowed)
        message(FATAL_ERROR "Layer boundary violation: ${chain} -> ${relative}")
    endif()
    file(STRINGS "${path}" includes REGEX "^[ \t]*#[ \t]*include")
    foreach(line IN LISTS includes)
        string(REGEX MATCH "[<\"]([^>\"]+)[>\"]" match "${line}")
        if(NOT match)
            continue()
        endif()
        set(include "${CMAKE_MATCH_1}")
        if(include MATCHES "^(imgui|GLFW/|GL/|X11/|gtk/|gdk/|gio/|wayland)")
            message(FATAL_ERROR "Desktop dependency from ${origin}: ${chain} -> ${include}")
        endif()
        get_filename_component(name "${include}" NAME)
        string(SHA256 key "${name}")
        get_property(dependency GLOBAL PROPERTY "header_${key}")
        if(dependency)
            check_dependencies("${dependency}" "${origin}" "${chain} -> ${relative}")
        endif()
    endforeach()
endfunction()

foreach(path IN LISTS MINEBACKUP_DATA_CORE_SOURCES MINEBACKUP_RUNTIME_SOURCES MINEBACKUP_CLI_SOURCES)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Source manifest references missing file: ${path}")
    endif()
endforeach()
foreach(path IN LISTS MINEBACKUP_DATA_CORE_SOURCES)
    if(NOT path MATCHES "/src/(domain|infra)/")
        message(FATAL_ERROR "data_core contains upper-layer implementation: ${path}")
    endif()
endforeach()
foreach(path IN LISTS MINEBACKUP_RUNTIME_SOURCES)
    if(NOT path MATCHES "/src/runtime/")
        message(FATAL_ERROR "runtime source belongs to another layer: ${path}")
    endif()
endforeach()
foreach(path IN LISTS project_files)
    file(RELATIVE_PATH relative "${MINEBACKUP_SRC_DIR}" "${path}")
    string(REGEX MATCH "^[^/]+" layer "${relative}")
    if(layer MATCHES "^(domain|infra|runtime|cli)$")
        check_dependencies("${path}" "${layer}" "${relative}")
    endif()
endforeach()
message(STATUS "Five-layer transitive source/header boundary audit passed")
