# Authoritative explicit source manifest. Keep paths grouped by architectural role.
set(MINEBACKUP_MAIN_SOURCES ${MINEBACKUP_SRC_DIR}/desktop/app/MineBackup.cpp)
set(MINEBACKUP_CLI_SOURCES
	${MINEBACKUP_SRC_DIR}/cli/CliArguments.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliApplication.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliJobResult.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliRenderer.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliSignalHandler.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliToolBootstrap.cpp
	${MINEBACKUP_SRC_DIR}/cli/CliMain.cpp)

set(MINEBACKUP_DATA_CORE_SOURCES
    ${MINEBACKUP_SRC_DIR}/domain/OperationResult.cpp
    ${MINEBACKUP_SRC_DIR}/infra/AppPaths.cpp
    ${MINEBACKUP_SRC_DIR}/infra/PlayerDataPreservation.cpp
    ${MINEBACKUP_SRC_DIR}/infra/ArchiveRunner.cpp
    ${MINEBACKUP_SRC_DIR}/infra/AtomicFileWriter.cpp
    ${MINEBACKUP_SRC_DIR}/infra/BackupChangeDetector.cpp
    ${MINEBACKUP_SRC_DIR}/infra/DiagnosticLogExporter.cpp
    ${MINEBACKUP_SRC_DIR}/infra/ExternalToolManager.cpp
    ${MINEBACKUP_SRC_DIR}/infra/InterruptedTaskRecovery.cpp
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkCommandDispatcher.cpp
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkPackageManager.cpp
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkProtocol.cpp
    ${MINEBACKUP_SRC_DIR}/infra/KnownUserFolders.cpp
    ${MINEBACKUP_SRC_DIR}/infra/LegacyLocationDiscovery.cpp
    ${MINEBACKUP_SRC_DIR}/infra/LegacyLocationMigration.cpp
    ${MINEBACKUP_SRC_DIR}/infra/LegacyServicePolicy.cpp
    ${MINEBACKUP_SRC_DIR}/infra/Logging.cpp
    ${MINEBACKUP_SRC_DIR}/infra/NetworkService.cpp
    ${MINEBACKUP_SRC_DIR}/infra/PathIdentity.cpp
    ${MINEBACKUP_SRC_DIR}/infra/PathRuleSet.cpp
    ${MINEBACKUP_SRC_DIR}/infra/ProcessInspectionService.cpp
    ${MINEBACKUP_SRC_DIR}/infra/ProcessRunner.cpp
    ${MINEBACKUP_SRC_DIR}/infra/RcloneClient.cpp
    ${MINEBACKUP_SRC_DIR}/infra/ReadOnlyMappedFile.cpp
    ${MINEBACKUP_SRC_DIR}/infra/RemoteContentService.cpp
    ${MINEBACKUP_SRC_DIR}/infra/Sha256.cpp
    ${MINEBACKUP_SRC_DIR}/infra/SingleInstanceService.cpp
    ${MINEBACKUP_SRC_DIR}/infra/WorldIdentity.cpp
    ${MINEBACKUP_SRC_DIR}/infra/config/ConfigIniCodec.cpp
    ${MINEBACKUP_SRC_DIR}/infra/config/JobDocument.cpp
    ${MINEBACKUP_SRC_DIR}/infra/config/LegacyIniConfigCodec.cpp
    ${MINEBACKUP_SRC_DIR}/infra/config/PortableConfigDocument.cpp
    ${MINEBACKUP_SRC_DIR}/infra/storage/CloudHistoryAnalysis.cpp
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindFormat.cpp
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindHistoryStore.cpp
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindMetadataStore.cpp
    ${MINEBACKUP_SRC_DIR}/infra/text/FileName.cpp
    ${MINEBACKUP_SRC_DIR}/infra/text/text_to_text.cpp
)

set(MINEBACKUP_RUNTIME_SOURCES
    ${MINEBACKUP_SRC_DIR}/runtime/BackupSelection.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/BackupManager.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/BatchReadinessService.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ChainSafeRetention.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ConfigFactory.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ConfigSelection.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/HistoryRepository.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/HmclDiscoveryProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/HotRestoreCoordinator.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/JobRunner.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/KnownMinecraftLocationProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/LauncherDiscoveryUtils.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/MigrationCoordinator.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/MinecraftInstanceDiscoveryService.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/MinecraftInstanceInspector.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ModrinthDiscoveryProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/NeteaseMinecraftDiscoveryProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/Pcl2ProcessDiscoveryProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/PrismLauncherDiscoveryProvider.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileConfigCatalog.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileConfigRepository.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileKnotLinkCommands.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileManifest.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileRuntime.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileTransaction.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RestorePreservedPaths.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RestoreService.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RestoreWorkspace.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeCloudPostHook.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeFileLock.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeIntegration.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeRetentionService.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/TaskCoordinator.cpp
    ${MINEBACKUP_SRC_DIR}/runtime/WizardSession.cpp
)

set(MINEBACKUP_V15_DATA_SOURCES
    ${MINEBACKUP_SRC_DIR}/infra/legacy/LegacyMineBackup15Reader.cpp
)

set(MINEBACKUP_V15_DESKTOP_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/legacy/V15MigrationAdapter.cpp
)

set(MINEBACKUP_APPLICATION_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/app/Application.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/ApplicationActions.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/ApplicationEventRouter.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/AppearanceRuntime.cpp
	${MINEBACKUP_SRC_DIR}/desktop/app/ConfigBatchCreationService.cpp
	${MINEBACKUP_SRC_DIR}/desktop/app/DesktopUiSession.cpp
	${MINEBACKUP_SRC_DIR}/desktop/app/DesktopUiLifecycle.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/AppState.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/Globals.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/app/ImGuiRuntime.cpp
	${MINEBACKUP_SRC_DIR}/desktop/app/LaunchOptions.cpp
	${MINEBACKUP_SRC_DIR}/desktop/legacy/LegacyServiceCleanup.cpp
	${MINEBACKUP_SRC_DIR}/desktop/adapters/BackupManagerDesktop.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/BackupAuxiliary.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/BackupRestore.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/BackupRetention.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CloudHistorySync.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CloudPortableConfig.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CloudSyncService.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CoreValidation.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/GameSessionManager.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/HistoryManager.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/Broadcast.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/ConfigManager.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/KnotLinkServerManager.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/KnotLinkService.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/i18n.cpp
	${MINEBACKUP_SRC_DIR}/desktop/adapters/DesktopServices.cpp
)

set(MINEBACKUP_UI_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/ui/CommandConsole.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/HistoryDialogs.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/HistoryUI.cpp
	${MINEBACKUP_SRC_DIR}/desktop/ui/HistoryViewModel.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/LogPanel.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/MigrationReportUI.cpp
	${MINEBACKUP_SRC_DIR}/desktop/ui/MinecraftSetupUI.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUI.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIApplication.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIAppearance.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIConfig.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUISpecial.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIHotkeys.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/WizardUI.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/MainUI.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/WorldListController.cpp
	${MINEBACKUP_SRC_DIR}/desktop/ui/WorldListModel.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/ui/WorldListUI.cpp
)

set(MINEBACKUP_WINDOWS_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_win.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/platform/NativeDesktopServices.cpp
    ${MINEBACKUP_SRC_DIR}/infra/platform/NetworkBackend_win.cpp
)
set(MINEBACKUP_LINUX_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_linux.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/platform/NativeDesktopServices.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/platform/LinuxDesktopPortal.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/platform/LinuxDesktopPortal.h
    ${MINEBACKUP_SRC_DIR}/infra/platform/NetworkBackend_linux.cpp)
set(MINEBACKUP_MACOS_SOURCES
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_macos.cpp
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_macos_tray.mm
    ${MINEBACKUP_SRC_DIR}/desktop/platform/MacDesktopBridge.mm
    ${MINEBACKUP_SRC_DIR}/desktop/platform/NativeDesktopServices.cpp
    ${MINEBACKUP_SRC_DIR}/infra/platform/NetworkBackend_macos.mm)

set(MINEBACKUP_IMGUI_SOURCES
    ${MINEBACKUP_IMGUI_DIR}/imgui.cpp
    ${MINEBACKUP_IMGUI_DIR}/imgui_draw.cpp
    ${MINEBACKUP_IMGUI_DIR}/imgui_tables.cpp
    ${MINEBACKUP_IMGUI_DIR}/imgui_widgets.cpp
    ${MINEBACKUP_IMGUI_DIR}/imgui_impl_glfw.cpp
    ${MINEBACKUP_IMGUI_DIR}/imgui_impl_opengl3.cpp
)

set(MINEBACKUP_SPDLOG_SOURCES
    ${MINEBACKUP_SPDLOG_DIR}/src/async.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/bundled_fmtlib_format.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/cfg.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/color_sinks.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/file_sinks.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/spdlog.cpp
    ${MINEBACKUP_SPDLOG_DIR}/src/stdout_sinks.cpp
)

set(MINEBACKUP_DATA_CORE_HEADERS
    ${MINEBACKUP_SRC_DIR}/domain/CompressionPolicy.h
    ${MINEBACKUP_SRC_DIR}/domain/DataModels.h
    ${MINEBACKUP_SRC_DIR}/domain/JobModels.h
    ${MINEBACKUP_SRC_DIR}/domain/MinecraftTypes.h
    ${MINEBACKUP_SRC_DIR}/domain/ModVersion.h
    ${MINEBACKUP_SRC_DIR}/domain/OperationResult.h
    ${MINEBACKUP_SRC_DIR}/domain/ProcessModels.h
    ${MINEBACKUP_SRC_DIR}/infra/AppPaths.h
    ${MINEBACKUP_SRC_DIR}/infra/PlayerDataPreservation.h
    ${MINEBACKUP_SRC_DIR}/infra/ArchiveRunner.h
    ${MINEBACKUP_SRC_DIR}/infra/AtomicFileWriter.h
    ${MINEBACKUP_SRC_DIR}/infra/BackupChangeDetector.h
    ${MINEBACKUP_SRC_DIR}/infra/DiagnosticLogExporter.h
    ${MINEBACKUP_SRC_DIR}/infra/ExternalToolManager.h
    ${MINEBACKUP_SRC_DIR}/infra/InterruptedTaskRecovery.h
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkCommandDispatcher.h
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkPackageManager.h
    ${MINEBACKUP_SRC_DIR}/infra/KnotLinkProtocol.h
    ${MINEBACKUP_SRC_DIR}/infra/KnownUserFolders.h
    ${MINEBACKUP_SRC_DIR}/infra/LegacyLocationDiscovery.h
    ${MINEBACKUP_SRC_DIR}/infra/LegacyLocationMigration.h
    ${MINEBACKUP_SRC_DIR}/infra/LegacyServicePolicy.h
    ${MINEBACKUP_SRC_DIR}/infra/Logging.h
    ${MINEBACKUP_SRC_DIR}/infra/NetworkService.h
    ${MINEBACKUP_SRC_DIR}/infra/PathIdentity.h
    ${MINEBACKUP_SRC_DIR}/infra/PathRuleSet.h
    ${MINEBACKUP_SRC_DIR}/infra/ProcessInspectionService.h
    ${MINEBACKUP_SRC_DIR}/infra/ProcessRunner.h
    ${MINEBACKUP_SRC_DIR}/infra/ProcessRunnerTestAccess.h
    ${MINEBACKUP_SRC_DIR}/infra/RcloneClient.h
    ${MINEBACKUP_SRC_DIR}/infra/ReadOnlyMappedFile.h
    ${MINEBACKUP_SRC_DIR}/infra/RemoteContentService.h
    ${MINEBACKUP_SRC_DIR}/infra/Sha256.h
    ${MINEBACKUP_SRC_DIR}/infra/SingleInstanceService.h
    ${MINEBACKUP_SRC_DIR}/infra/WorldIdentity.h
    ${MINEBACKUP_SRC_DIR}/infra/config/ConfigIniCodec.h
    ${MINEBACKUP_SRC_DIR}/infra/config/JobDocument.h
    ${MINEBACKUP_SRC_DIR}/infra/config/LegacyIniConfigCodec.h
    ${MINEBACKUP_SRC_DIR}/infra/config/PortableConfigDocument.h
    ${MINEBACKUP_SRC_DIR}/infra/legacy/LegacyMineBackup15Reader.h
    ${MINEBACKUP_SRC_DIR}/infra/platform/NetworkBackendFactory.h
    ${MINEBACKUP_SRC_DIR}/infra/platform/PlatformCompat.h
    ${MINEBACKUP_SRC_DIR}/infra/storage/CloudHistoryAnalysis.h
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindFormat.h
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindHistoryStore.h
    ${MINEBACKUP_SRC_DIR}/infra/storage/FolderRewindMetadataStore.h
    ${MINEBACKUP_SRC_DIR}/infra/text/FileName.h
    ${MINEBACKUP_SRC_DIR}/infra/text/text_to_text.h
)

set(MINEBACKUP_DATA_CORE_INCLUDE_DIRS
    ${MINEBACKUP_SRC_DIR}/domain
    ${MINEBACKUP_SRC_DIR}/infra
    ${MINEBACKUP_SRC_DIR}/infra/config
    ${MINEBACKUP_SRC_DIR}/infra/legacy
    ${MINEBACKUP_SRC_DIR}/infra/platform
    ${MINEBACKUP_SRC_DIR}/infra/storage
    ${MINEBACKUP_SRC_DIR}/infra/text
)

set(MINEBACKUP_RUNTIME_HEADERS
    ${MINEBACKUP_SRC_DIR}/runtime/BackupManagerInternal.h
    ${MINEBACKUP_SRC_DIR}/runtime/BackupSelection.h
    ${MINEBACKUP_SRC_DIR}/runtime/BackupService.h
    ${MINEBACKUP_SRC_DIR}/runtime/BatchReadinessService.h
    ${MINEBACKUP_SRC_DIR}/runtime/ChainSafeRetention.h
    ${MINEBACKUP_SRC_DIR}/runtime/ConfigFactory.h
    ${MINEBACKUP_SRC_DIR}/runtime/ConfigSelection.h
    ${MINEBACKUP_SRC_DIR}/runtime/HistoryRepository.h
    ${MINEBACKUP_SRC_DIR}/runtime/HmclDiscoveryProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/HotRestoreCoordinator.h
    ${MINEBACKUP_SRC_DIR}/runtime/JobRunner.h
    ${MINEBACKUP_SRC_DIR}/runtime/KnownMinecraftLocationProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/LauncherDiscoveryUtils.h
    ${MINEBACKUP_SRC_DIR}/runtime/MigrationCoordinator.h
    ${MINEBACKUP_SRC_DIR}/runtime/MinecraftDiscovery.h
    ${MINEBACKUP_SRC_DIR}/runtime/MinecraftInstanceDiscoveryService.h
    ${MINEBACKUP_SRC_DIR}/runtime/MinecraftInstanceInspector.h
    ${MINEBACKUP_SRC_DIR}/runtime/ModrinthDiscoveryProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/NeteaseMinecraftDiscoveryProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/Pcl2ProcessDiscoveryProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/PrismLauncherDiscoveryProvider.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileConfigCatalog.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileConfigRepository.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileKnotLinkCommands.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileManifest.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileRuntime.h
    ${MINEBACKUP_SRC_DIR}/runtime/ProfileTransaction.h
    ${MINEBACKUP_SRC_DIR}/runtime/RestorePreservedPaths.h
    ${MINEBACKUP_SRC_DIR}/runtime/RestoreService.h
    ${MINEBACKUP_SRC_DIR}/runtime/RestoreWorkspace.h
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeCloudPostHook.h
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeFileLock.h
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeIntegration.h
    ${MINEBACKUP_SRC_DIR}/runtime/RuntimeRetentionService.h
    ${MINEBACKUP_SRC_DIR}/runtime/TaskCoordinator.h
    ${MINEBACKUP_SRC_DIR}/runtime/WizardSession.h
)

set(MINEBACKUP_RUNTIME_INCLUDE_DIRS
    ${MINEBACKUP_SRC_DIR}/runtime
)

set(MINEBACKUP_DESKTOP_HEADERS
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/BackupManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/Broadcast.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CloudSyncInternal.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CloudSyncService.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/ConfigManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/CoreValidation.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/GameSessionManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/HistoryManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/KnotLinkServerManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/KnotLinkService.h
    ${MINEBACKUP_SRC_DIR}/desktop/adapters/i18n.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/AppState.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/AppearanceRuntime.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/Application.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/ApplicationActions.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/ApplicationEventRouter.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/ConfigBatchCreationService.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/DesktopRuntimeState.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/DesktopUiLifecycle.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/DesktopUiSession.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/Globals.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/ImGuiRuntime.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/LaunchOptions.h
    ${MINEBACKUP_SRC_DIR}/desktop/app/MainUI.h
    ${MINEBACKUP_SRC_DIR}/desktop/legacy/LegacyServiceCleanup.h
    ${MINEBACKUP_SRC_DIR}/desktop/legacy/V15MigrationAdapter.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/DesktopPlatform.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/DesktopServices.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/LinuxDesktopPortal.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/MacDesktopBridge.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/NativeDesktopServices.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_linux.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_macos.h
    ${MINEBACKUP_SRC_DIR}/desktop/platform/Platform_win.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/CommandConsole.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/HistoryDialogs.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/HistoryViewModel.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/IconsFontAwesome6.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/LogPanel.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/MainUiController.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/MigrationReportUI.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/MinecraftSetupUI.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsAutoSave.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUI.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIHotkeys.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/SettingsUIPrivate.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/ThemeManager.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/ThemePalette.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/UIHelpers.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/WorldListController.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/WorldListModel.h
    ${MINEBACKUP_SRC_DIR}/desktop/ui/imgui-all.h
)

set(MINEBACKUP_DESKTOP_INCLUDE_DIRS
    ${MINEBACKUP_SRC_DIR}/desktop/adapters
    ${MINEBACKUP_SRC_DIR}/desktop/app
    ${MINEBACKUP_SRC_DIR}/desktop/legacy
    ${MINEBACKUP_SRC_DIR}/desktop/platform
    ${MINEBACKUP_SRC_DIR}/desktop/ui
)
