function(minebackup_generate_artifacts output_dir source_dir)
    file(MAKE_DIRECTORY "${output_dir}")
    set(MINEBACKUP_ARTIFACT_SOURCE_DIR "${source_dir}")
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/MineBackupVersion.h.in ${output_dir}/MineBackupVersion.h @ONLY)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/MineBackupVersion.rc.inc.in ${output_dir}/MineBackupVersion.rc.inc @ONLY)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/MineBackup.rc.in ${output_dir}/MineBackup.rc @ONLY)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/MineBackupCli.rc.in ${output_dir}/MineBackupCli.rc @ONLY)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/io.github.leafuke.MineBackup.desktop.in ${output_dir}/io.github.leafuke.MineBackup.desktop @ONLY)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/templates/Info.plist.in ${output_dir}/Info.plist @ONLY)
endfunction()
